<Project>
  <PropertyGroup Label="build">
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Label="pakcage-common">
    <Version>3.0.1</Version>
    <Authors>Uta Sugane</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/Uta-member/CSStack.TADA</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Uta-member/CSStack.TADA</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

</Project>
